services:
  db:
    image: postgres:15
    container_name: audit-db
    restart: always
    environment:
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: audit_pass
      POSTGRES_DB: auditdb
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
