version: "3.9"

services:
  db:
    image: postgres:15
    container_name: audit-db
    restart: always
    environment:
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: audit_pass
      POSTGRES_DB: auditdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.api
    container_name: audit-api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
